name: Build docker
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build image job
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          dockerFile: Dockerfile
          imageName: jor1024/smartdns
          platform: linux/amd64,linux/arm64 # 你准备构建的镜像平台
          tag: latest # 默认latest，可以针对平台，修改tag
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }} # docker hub userid
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }} # docker hub password